spring:
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/hotel_db}
    username: ${PG_USER:spring_service}
    password: ${PG_PASS:1234}
jpa:
  hibernate:
    ddl-auto: update

server:
  port: 8080
